// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	lists := []*ListNode{buildListNode([]int{1, 4, 5}), buildListNode([]int{1, 3, 4}), buildListNode([]int{2, 6})}
	got := mergeKLists(lists)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		lists := []*ListNode{buildListNode([]int{1, 4, 5}), buildListNode([]int{1, 3, 4}), buildListNode([]int{2, 6})}
		got := mergeKLists(lists)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		lists := []*ListNode{}
		got := mergeKLists(lists)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_3", func(t *testing.T) {
		lists := []*ListNode{buildListNode([]int{})}
		got := mergeKLists(lists)
		t.Logf("got = %#v", got)
	})
}
