// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	n := 4
	edges := [][]int{{1, 0}, {1, 2}, {1, 3}}
	got := findMinHeightTrees(n, edges)
	fmt.Printf("got = %#v", got)
}
