// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	n := 4
	edges := [][]int{{1, 0}, {1, 2}, {1, 3}}
	got := findMinHeightTrees(n, edges)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		n := 4
		edges := [][]int{{1, 0}, {1, 2}, {1, 3}}
		got := findMinHeightTrees(n, edges)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		n := 6
		edges := [][]int{{3, 0}, {3, 1}, {3, 2}, {3, 4}, {5, 4}}
		got := findMinHeightTrees(n, edges)
		t.Logf("got = %#v", got)
	})
}
