// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "fmt"

func main() {
	nums := []int{2, 7, 11, 15}
	target := 9
	got := twoSum(nums, target)
	fmt.Printf("got = %#v", got)
}
