// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "fmt"

func main() {
	nums := []int{1, 12, -5, -6, 50, 3}
	k := 4
	got := findMaxAverage(nums, k)
	fmt.Printf("got = %#v", got)
}
