// Auto-generated by scripts/generate-go-tests.py from solution.tests.dat
package main

import "testing"

func TestDebug(t *testing.T) {
	nums := []int{1, 12, -5, -6, 50, 3}
	k := 4
	got := findMaxAverage(nums, k)
	t.Logf("got = %#v", got)
}

func TestSamples(t *testing.T) {
	t.Run("sample_1", func(t *testing.T) {
		nums := []int{1, 12, -5, -6, 50, 3}
		k := 4
		got := findMaxAverage(nums, k)
		t.Logf("got = %#v", got)
	})
	t.Run("sample_2", func(t *testing.T) {
		nums := []int{5}
		k := 1
		got := findMaxAverage(nums, k)
		t.Logf("got = %#v", got)
	})
}
