// Auto-generated by scripts/generate-go-tests.py from main.tests.dat
package main

import "fmt"

func main() {
	heights := []int{2, 1, 5, 6, 2, 3}
	got := largestRectangleArea(heights)
	fmt.Printf("got = %#v", got)
}
